import { Location } from './types';
import { getCachedPhotos } from './services/googlePlacesService';

// Helper to build location with Google Places images (or fallback)
const buildLocation = (id: number, data: Omit<Location, 'image' | 'gallery'>): Location => {
  // Try to get cached photos from Google Places
  const cachedPhotos = getCachedPhotos(id);
  
  if (cachedPhotos && cachedPhotos.length > 0) {
    return {
      ...data,
      id,
      image: cachedPhotos[0],
      gallery: cachedPhotos.slice(0, 4)
    };
  }
  
  // Fallback to placeholder until Google Places photos are loaded
  return {
    ...data,
    id,
    image: '/images/fallback.png',
    gallery: ['/images/fallback.png', '/images/fallback.png', '/images/fallback.png']
  };
};

export const locations: Location[] = [
    // ORIGINAL 50 LOCATIONS
    buildLocation(1, { name: "Klyde Warren Park", category: "Park", lat: 32.7891, lng: -96.8015, address: "2012 Woodall Rodgers Fwy, Dallas, TX 75201", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { all: "06:00-23:00" }, rating: 4.8, reviewCount: 1250, reviewHighlights: ["Great food trucks", "Clean and safe", "Splash pad is amazing"], tips: ["Check their website for free events.", "Pack a picnic to save money.", "The splash pad is a huge hit in the summer."], events: [{title: "Yoga in the Park", date: "Saturdays at 10 AM", description: "A free, all-levels yoga class on the lawn.", cost: "Free"}, {title: "Music on the Square", date: "Friday, Oct 17th at 7 PM", description: "Live performance by a local jazz trio.", cost: "Free"}] }),
    buildLocation(2, { name: "Perot Museum of Nature and Science", category: "Museum", lat: 32.7877, lng: -96.8058, address: "2201 N Field St, Dallas, TX 75201", ageGroups: ["Kids", "Teens"], price: "$$$", ticketInfo: { Adult: 25, Youth: 18, Senior: 23 }, hours: { Mon: "10:00-17:00", Tue: "10:00-17:00", Wed: "10:00-17:00", Thu: "10:00-17:00", Fri: "10:00-17:00", Sat: "10:00-18:00", Sun: "11:00-17:00" }, rating: 4.9, reviewCount: 980, reviewHighlights: ["Kids museum is fantastic", "Very interactive exhibits", "Plan for a full day"], tips: ["Book tickets online in advance.", "The children's museum is perfect for kids under 5.", "Don't miss the earthquake simulator."] }),
    buildLocation(3, { name: "Fort Worth Botanic Garden", category: "Outdoors", lat: 32.7397, lng: -97.3639, address: "3220 Botanic Garden Blvd, Fort Worth, TX 76107", ageGroups: ["Toddlers", "Kids", "Teens"], price: "$$", ticketInfo: { Adult: 12, Child: 6 }, hours: { all: "08:00-18:00" }, rating: 4.7, reviewCount: 750, reviewHighlights: ["Japanese Garden is a must-see", "Peaceful and beautiful", "Lots of walking"], tips: ["The Japanese Garden has a separate admission.", "Bring comfortable shoes.", "Feed the koi fish in the ponds."] }),
    buildLocation(4, { name: "Adventure World Park", category: "Playground", lat: 32.9360, lng: -97.0789, address: "7451 Starnes Rd, North Richland Hills, TX 76182", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "06:00-22:00" }, rating: 4.9, reviewCount: 430, reviewHighlights: ["Great for all ages", "Soft rubber ground", "Can get crowded"], tips: ["The ground is a soft, rubbery material.", "Go on a weekday morning to avoid crowds.", "Clean restrooms and shaded picnic areas."] }),
    buildLocation(5, { name: "Crayola Experience Plano", category: "Indoor", lat: 33.0818, lng: -96.8242, address: "6121 W Park Blvd, Plano, TX 75093", ageGroups: ["Toddlers", "Kids"], price: "$$$", ticketInfo: { General: 28.99 }, hours: { Mon: "10:00-18:00", Tue: "10:00-18:00", Wed: "10:00-18:00", Thu: "10:00-18:00", Fri: "10:00-20:00", Sat: "10:00-20:00", Sun: "11:00-18:00" }, rating: 4.5, reviewCount: 810, reviewHighlights: ["So many activities", "Perfect for rainy days", "A bit pricey"], tips: ["Great for a rainy or extremely hot day.", "Plan to spend at least 3-4 hours.", "You get to take home your creations."] }),
    buildLocation(6, { name: "Hope Park", category: "Playground", lat: 33.0485, lng: -96.7978, address: "8000 McKinney Rd, Frisco, TX 75034", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "08:00-20:00" }, rating: 4.9, reviewCount: 650, reviewHighlights: ["Best splash pad", "Fully enclosed tot lot", "Something for everyone"], tips: ["Bring swimsuits and towels for the splash pad!", "The 'tot lot' is great for little runners.", "It's huge, so keep an eye on your kids."] }),
    buildLocation(7, { name: "Dallas World Aquarium", category: "Museum", lat: 32.7836, lng: -96.8066, address: "1801 N Griffin St, Dallas, TX 75202", ageGroups: ["Toddlers", "Kids", "Teens"], price: "$$$", ticketInfo: { Adult: 29.95, Child: 19.95 }, hours: { all: "09:00-17:00" }, rating: 4.6, reviewCount: 1100, reviewHighlights: ["Immersive rainforest", "Long entry lines", "Shark tunnel is cool"], tips: ["Arrive early or on a weekday to avoid lines.", "Follow the recommended path.", "Don't miss the manatee feeding time."] }),
    buildLocation(8, { name: "Fort Worth Zoo", category: "Outdoors", lat: 32.7210, lng: -97.3568, address: "1989 Colonial Pkwy, Fort Worth, TX 76110", ageGroups: ["Toddlers", "Kids", "Teens"], price: "$$$", ticketInfo: { Adult: 18, Child: 14 }, hours: { all: "10:00-17:00" }, rating: 4.8, reviewCount: 1500, reviewHighlights: ["Clean and well-maintained", "Texas Wild! exhibit is great", "Lots of shade"], tips: ["Buy tickets online.", "The train ride is a fun add-on.", "Half-price Wednesdays can be very crowded."] }),
    buildLocation(9, { name: "Play Street Museum", category: "Indoor", lat: 33.0463, lng: -96.8281, address: "Multiple DFW Locations", ageGroups: ["Toddlers", "Kids"], price: "$$", ticketInfo: { Child: 13, note: "per session" }, hours: { all: "09:00-17:00" }, rating: 4.9, reviewCount: 320, reviewHighlights: ["Perfect for toddlers", "Clean and well-themed", "Must book session online"], tips: ["Reservations are required.", "Sessions are timed, so be punctual.", "Check their calendar for special events."] }),
    buildLocation(10, { name: "Arbor Hills Nature Preserve", category: "Outdoors", lat: 33.0877, lng: -96.8622, address: "6701 W Parker Rd, Plano, TX 75093", ageGroups: ["Kids", "Teens"], price: "Free", hours: { all: "05:00-23:00" }, rating: 4.8, reviewCount: 950, reviewHighlights: ["Great hiking trails", "Observation tower views", "Playground for kids"], tips: ["Bring bug spray in the summer.", "The observation tower offers great views of Plano.", "Good spot for family photos."] }),
    buildLocation(11, { name: "Dallas Arboretum and Botanical Garden", category: "Outdoors", lat: 32.8180, lng: -96.7169, address: "8525 Garland Rd, Dallas, TX 75218", ageGroups: ["Toddlers", "Kids", "Teens"], price: "$$", ticketInfo: { Adult: 20, Child: 12 }, hours: { all: "09:00-17:00" }, rating: 4.8, reviewCount: 1300, reviewHighlights: ["Beautiful seasonal displays", "Rory Meyers Children's Garden", "Great photo ops"], tips: ["The Children's Adventure Garden requires a separate ticket.", "Bring a wagon for little kids.", "Check for seasonal festivals like Dallas Blooms and Autumn at the Arboretum."], events: [{title: "Autumn at the Arboretum", date: "Through Nov 5th", description: "One of the nation's best pumpkin festivals with over 100,000 pumpkins, gourds and squash.", cost: "Included with general admission."}] }),
    buildLocation(12, { name: "White Rock Lake Park", category: "Park", lat: 32.8250, lng: -96.7090, address: "8300 E Lawther Dr, Dallas, TX 75218", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { all: "06:00-23:00" }, rating: 4.7, reviewCount: 900, reviewHighlights: ["Great for biking", "Lovely sunsets", "Playground near the Bath House"], tips: ["The main loop is over 9 miles long.", "Rent kayaks or paddleboards for fun on the water.", "The playground by the Bath House Cultural Center is a popular spot."] }),
    buildLocation(13, { name: "Fort Worth Museum of Science and History", category: "Museum", lat: 32.7448, lng: -97.3702, address: "1600 Gendy St, Fort Worth, TX 76107", ageGroups: ["Toddlers", "Kids", "Teens"], price: "$$", ticketInfo: { Adult: 16, Child: 12 }, hours: { Tue:"10:00-17:00", Wed:"10:00-17:00", Thu:"10:00-17:00", Fri:"10:00-17:00", Sat:"10:00-17:00", Sun:"12:00-17:00", Mon:"Closed" }, rating: 4.6, reviewCount: 850, reviewHighlights: ["Children's museum inside", "DinoLabs is awesome", "IMAX theater is a plus"], tips: ["Great for younger kids (2-8).", "Check Noble Planetarium show times.", "Can be done in a few hours."] }),
    buildLocation(14, { name: "Sundance Square", category: "Outdoors", lat: 32.7535, lng: -97.3323, address: "420 Main St, Fort Worth, TX 76102", ageGroups: ["Kids", "Teens"], price: "Free", hours: { all: "00:00-23:59" }, rating: 4.8, reviewCount: 1100, reviewHighlights: ["Beautiful fountains", "Great restaurants", "Clean and safe area"], tips: ["Kids love playing in the splash fountains in the summer.", "Often has free events and concerts.", "A great place for a family walk in the evening."] }),
    buildLocation(15, { name: "Trinity Park", category: "Park", lat: 32.7500, lng: -97.3560, address: "2401 University Dr, Fort Worth, TX 76107", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { all: "05:00-23:30" }, rating: 4.7, reviewCount: 950, reviewHighlights: ["Huge playground", "Miniature train ride", "Access to Trinity Trails"], tips: ["The Fort Worth Adventure Park playground is massive.", "The Trinity Park miniature train is a classic.", "Perfect for picnics and flying kites."] }),
    buildLocation(16, { name: "Dream Park", category: "Playground", lat: 32.7512, lng: -97.3585, address: "2401 University Dr, Fort Worth, TX 76107", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "05:00-23:30" }, rating: 4.9, reviewCount: 500, reviewHighlights: ["Inclusive for all abilities", "So many things to do", "Can get very busy"], tips: ["Located inside Trinity Park.", "Designed to be accessible for children of all abilities.", "Rubber surfaces and lots of ramps."] }),
    buildLocation(17, { name: "Bureau of Engraving and Printing", category: "Museum", lat: 32.8360, lng: -97.3385, address: "9000 Blue Mound Rd, Fort Worth, TX 76131", ageGroups: ["Kids", "Teens"], price: "Free", hours: { Tue: "08:30-17:30", Wed: "08:30-17:30", Thu: "08:30-17:30", Fri: "08:30-17:30", Sat:"Closed", Sun:"Closed", Mon:"Closed" }, rating: 4.6, reviewCount: 600, reviewHighlights: ["See money being printed!", "Very educational", "Free tour"], tips: ["One of only two 'money factories' in the US.", "Self-guided tour along an elevated walkway.", "Great for school-aged kids interested in how things are made."] }),
    buildLocation(18, { name: "River Legacy Parks", category: "Park", lat: 32.7758, lng: -97.1350, address: "701 NW Green Oaks Blvd, Arlington, TX 76006", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { all: "05:00-22:00" }, rating: 4.8, reviewCount: 1000, reviewHighlights: ["Amazing nature trails", "Huge playgrounds", "Science Center is cool"], tips: ["The park has multiple playgrounds; some are more hidden than others.", "The Living Science Center is a great indoor option (has an admission fee).", "Excellent for paved trail bike rides."] }),
    buildLocation(19, { name: "Levitt Pavilion for the Performing Arts", category: "Outdoors", lat: 32.7338, lng: -97.1086, address: "100 W Abram St, Arlington, TX 76010", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { all: "Varies" }, rating: 4.7, reviewCount: 450, reviewHighlights: ["Free concerts!", "Family-friendly atmosphere", "Bring your own chairs"], tips: ["Offers over 50 free outdoor concerts a year.", "Check their schedule online.", "Bring blankets, lawn chairs, and a cooler for a perfect evening."], events: [{title: "Family Movie Night: The Super Mario Bros. Movie", date: "Friday, Oct 24th at 8 PM", description: "Bring your blankets and enjoy a free screening under the stars.", cost: "Free"}] }),
    buildLocation(20, { name: "Randol Mill Park", category: "Park", lat: 32.7634, lng: -97.0850, address: "1901 W Randol Mill Rd, Arlington, TX 76012", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "05:00-22:00" }, rating: 4.6, reviewCount: 550, reviewHighlights: ["Great duck pond", "Multiple playgrounds", "Nice walking trails"], tips: ["A classic city park with lots to do.", "The playground is partially shaded.", "Kids love feeding the ducks (bring birdseed, not bread!)."] }),
    buildLocation(21, { name: "Chandor Gardens", category: "Outdoors", lat: 32.7618, lng: -97.7940, address: "711 W Lee Ave, Weatherford, TX 76086", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Admission: 5 }, hours: { Mon:"09:00-17:00", Tue:"09:00-17:00", Sat:"09:00-17:00", Sun:"12:00-16:00", Wed:"Closed", Thu:"Closed", Fri:"Closed" }, rating: 4.8, reviewCount: 300, reviewHighlights: ["Hidden gem", "Beautiful and tranquil", "Fun to explore"], tips: ["A unique garden blending Chinese architecture with English gardens.", "Not a playground, but great for a peaceful walk with older kids.", "Lots of little nooks and crannies to discover."] }),
    buildLocation(22, { name: "Clark Gardens", category: "Outdoors", lat: 32.6180, lng: -97.9015, address: "567 Maddux Rd, Weatherford, TX 76088", ageGroups: ["Toddlers", "Kids", "Teens"], price: "$$", ticketInfo: { Adult: 9, Child: 5 }, hours: { Mon:"08:00-17:00", Tue:"08:00-17:00", Wed:"08:00-17:00", Thu:"08:00-17:00", Fri:"08:00-17:00", Sat:"08:00-17:00", Sun:"10:00-17:00"}, rating: 4.7, reviewCount: 400, reviewHighlights: ["G-scale model trains!", "Beautiful flowers", "Lots of space to run"], tips: ["The model train exhibit is a huge draw for kids.", "Check for their events like the Monarch butterfly release.", "Has some peacocks roaming the grounds."] }),
    buildLocation(23, { name: "Holland Lake Park", category: "Park", lat: 32.7510, lng: -97.8080, address: "1419 Holland Lake Dr, Weatherford, TX 76086", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "06:00-22:00" }, rating: 4.6, reviewCount: 350, reviewHighlights: ["Nice playground", "Disc golf course", "Fishing pier"], tips: ["A lovely community park.", "The playground is well-maintained.", "Good for a quick stop to let kids burn off energy."] }),
    buildLocation(24, { name: "The National Vietnam War Museum", category: "Museum", lat: 32.6375, lng: -97.8931, address: "12685 E US Highway 180, Mineral Wells, TX 76067", ageGroups: ["Teens"], price: "$", ticketInfo: { Admission: 5, note: "donation suggested" }, hours: { Wed:"09:00-17:00", Thu:"09:00-17:00", Fri:"09:00-17:00", Sat:"09:00-17:00", Sun:"12:00-16:00", Mon:"Closed", Tue:"Closed"}, rating: 4.8, reviewCount: 250, reviewHighlights: ["Very moving", "Lots of historical vehicles", "Important history lesson"], tips: ["Best for older kids and teens interested in history.", "Features a half-scale replica of the Vietnam Veterans Memorial wall.", "Mostly outdoors, so check the weather."] }),
    buildLocation(25, { name: "National Videogame Museum", category: "Museum", lat: 33.0475, lng: -96.8277, address: "8004 Dallas Pkwy, Frisco, TX 75034", ageGroups: ["Kids", "Teens"], price: "$$", ticketInfo: { Adult: 12, Child: 10 }, hours: { Tue: "10:00-17:00", Wed: "10:00-17:00", Thu: "10:00-17:00", Fri: "10:00-20:00", Sat: "10:00-20:00", Sun: "12:00-17:00", Mon:"Closed"}, rating: 4.7, reviewCount: 700, reviewHighlights: ["Retro arcade is awesome", "Nostalgia overload", "Interactive history"], tips: ["You get tokens for the arcade with admission.", "Great for parents who grew up with classic Nintendo and Atari.", "The giant Pong game is a family favorite."] }),
    buildLocation(26, { name: "Heard Natural Science Museum & Wildlife Sanctuary", category: "Outdoors", lat: 33.1670, lng: -96.6110, address: "1 Nature Pl, McKinney, TX 75069", ageGroups: ["Kids", "Teens"], price: "$$", ticketInfo: { Adult: 12, Child: 9 }, hours: { Tue: "09:00-17:00", Wed: "09:00-17:00", Thu: "09:00-17:00", Fri: "09:00-17:00", Sat: "09:00-17:00", Sun: "13:00-17:00", Mon:"Closed"}, rating: 4.6, reviewCount: 650, reviewHighlights: ["Animatronic dinosaurs", "Butterfly garden", "Nice nature trails"], tips: ["Check the schedule for the Dinosaurs Live! exhibit.", "The butterfly house is beautiful.", "Wear good walking shoes for the trails."] }),
    buildLocation(27, { name: "Grapevine Vintage Railroad", category: "Attraction", lat: 32.9420, lng: -97.0768, address: "705 S Main St, Grapevine, TX 76051", ageGroups: ["Toddlers", "Kids"], price: "$$$", ticketInfo: { Adult: 20, Child: 16, note: "prices vary" }, hours: { all: "Varies" }, rating: 4.5, reviewCount: 550, reviewHighlights: ["Authentic vintage train", "Fun for kids", "Special events are great"], tips: ["Check for special event rides like the North Pole Express at Christmas.", "The ride to the Fort Worth Stockyards is a popular trip.", "Book tickets far in advance for holidays."] }),
    buildLocation(28, { name: "LEGOLAND Discovery Center", category: "Indoor", lat: 32.9602, lng: -97.0425, address: "3000 Grapevine Mills Pkwy, Grapevine, TX 76051", ageGroups: ["Toddlers", "Kids"], price: "$$$", ticketInfo: { General: 24.99, note: "online price" }, hours: { all: "10:00-17:00" }, rating: 4.3, reviewCount: 900, reviewHighlights: ["Best for younger kids", "Can get very crowded", "Rides and 4D movie"], tips: ["Located inside Grapevine Mills mall.", "Best for kids 3-10.", "Buy tickets online to guarantee entry as it often sells out."] }),
    buildLocation(29, { name: "Sea Life Grapevine Aquarium", category: "Museum", lat: 32.9605, lng: -97.0420, address: "3000 Grapevine Mills Pkwy, Grapevine, TX 76051", ageGroups: ["Toddlers", "Kids"], price: "$$", ticketInfo: { Adult: 23.99, Child: 16.99 }, hours: { all: "10:00-17:00" }, rating: 4.4, reviewCount: 850, reviewHighlights: ["360-degree ocean tunnel", "Interactive rockpools", "Good for a couple hours"], tips: ["Located across from LEGOLAND in the mall.", "Combo tickets are available.", "The ocean tunnel is the main attraction."] }),
    buildLocation(30, { name: "NRH2O Family Water Park", category: "Waterpark", lat: 32.8368, lng: -97.2185, address: "9001 26 Blvd, North Richland Hills, TX 76180", ageGroups: ["Kids", "Teens"], price: "$$", ticketInfo: { General: 32.99 }, hours: { all: "Varies (Seasonal)" }, rating: 4.6, reviewCount: 750, reviewHighlights: ["Clean and fun", "Not too overwhelming", "Free cooler policy"], tips: ["A smaller, more manageable water park than the giant ones.", "You can bring your own coolers with food and drinks, which saves a lot of money.", "Check for discount days or twilight hours."] }),
    buildLocation(31, { name: "Celebration Park", category: "Playground", lat: 33.1119, lng: -96.6789, address: "701 Angel Pkwy, Allen, TX 75002", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "08:00-22:00" }, rating: 4.8, reviewCount: 600, reviewHighlights: ["Massive playground", "Splash pad in summer", "Lots of fields"], tips: ["The playground is huge and castle-themed.", "The sprayground is one of the best free ones in DFW.", "Can be very popular on weekends."] }),
    buildLocation(32, { name: "Kimbell Art Museum", category: "Museum", lat: 32.7485, lng: -97.3649, address: "3333 Camp Bowie Blvd, Fort Worth, TX 76107", ageGroups: ["Teens"], price: "Free", hours: { Tue:"10:00-17:00", Wed:"10:00-17:00", Thu:"10:00-17:00", Fri:"12:00-20:00", Sat:"10:00-17:00", Sun:"12:00-17:00", Mon:"Closed" }, rating: 4.9, reviewCount: 500, reviewHighlights: ["World-class art collection", "Stunning architecture", "Free general admission"], tips: ["Permanent collection is free to view.", "A great 'intro to art' museum as it's small and high-quality.", "The Louis Kahn building is a masterpiece."] }),
    buildLocation(33, { name: "The Shops at Clearfork", category: "Outdoors", lat: 32.7153, lng: -97.4124, address: "5188 Monahans Ave, Fort Worth, TX 76109", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "Varies" }, rating: 4.5, reviewCount: 400, reviewHighlights: ["Great green space", "Splash pad", "High-end shopping"], tips: ["The central green area has a splash pad and is perfect for letting kids run around while parents relax.", "Many restaurants have patios overlooking the green.", "Check for seasonal events."] }),
    buildLocation(34, { name: "Parr Park", category: "Playground", lat: 32.9150, lng: -97.0945, address: "3010 Parr Ln, Grapevine, TX 76051", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "06:00-22:00" }, rating: 4.7, reviewCount: 350, reviewHighlights: ["Huge playground area", "Sprayground is fun", "Shaded spots"], tips: ["The playground has a unique, modern design.", "The sprayground is a popular summer destination.", "Lots of walking trails connect to the park."] }),
    buildLocation(35, { name: "Fritz Park Petting Farm", category: "Attraction", lat: 32.8468, lng: -96.9458, address: "312 E Vilbig St, Irving, TX 75060", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "Varies (Seasonal)" }, rating: 4.6, reviewCount: 300, reviewHighlights: ["Free admission", "See farm animals", "Only open in summer"], tips: ["Only open June and July.", "A simple, old-fashioned petting farm.", "Great for a short visit with little ones."] }),
    buildLocation(36, { name: "Epic Waters Indoor Waterpark", category: "Waterpark", lat: 32.6848, lng: -96.9930, address: "2970 Epic Place, Grand Prairie, TX 75052", ageGroups: ["Kids", "Teens"], price: "$$", ticketInfo: { General: 34, note: "prices vary" }, hours: { all: "Varies" }, rating: 4.4, reviewCount: 950, reviewHighlights: ["Open year-round", "Fun slides", "Can get very loud"], tips: ["Being indoors is a huge plus for rainy or cold days.", "The retractable roof opens on nice days.", "Look for deals on their website, especially for non-peak times."] }),
    buildLocation(37, { name: "Fort Worth Water Gardens", category: "Park", lat: 32.7483, lng: -97.3308, address: "1502 Commerce St, Fort Worth, TX 76102", ageGroups: ["Kids", "Teens"], price: "Free", hours: { all: "07:00-22:00" }, rating: 4.7, reviewCount: 1200, reviewHighlights: ["Unique and futuristic", "Cool to walk through", "Great for photos"], tips: ["An urban oasis with amazing concrete and water structures.", "The 'active pool' is the main attraction where you can walk down the steps surrounded by cascading water.", "Keep a close eye on small children."] }),
    buildLocation(38, { name: "Stockyards National Historic District", category: "Attraction", lat: 32.7885, lng: -97.3480, address: "131 E Exchange Ave, Fort Worth, TX 76164", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { 'Cattle Drive': 'Free', Maze: 6 }, hours: { all: "Varies" }, rating: 4.6, reviewCount: 2000, reviewHighlights: ["Twice-daily cattle drive", "Old West feel", "Lots of shops"], tips: ["The cattle drive is the main event for families, check the times online.", "Can be touristy, but kids love the cowboy atmosphere.", "The Cowtown Cattlepen Maze is a fun add-on."] }),
    buildLocation(39, { name: "Burger's Lake", category: "Waterpark", lat: 32.7208, lng: -97.4691, address: "1200 Meandering Rd, Fort Worth, TX 76114", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Admission: 20, note: "cash only" }, hours: { all: "Varies (Seasonal)" }, rating: 4.5, reviewCount: 600, reviewHighlights: ["Old-school swimming hole", "Picnic areas and grills", "Spring-fed lake"], tips: ["A 30-acre park with a spring-fed lake for swimming.", "Features slides, a trapeze, and diving boards.", "Cash only, so come prepared."] }),
    buildLocation(40, { name: "Benbrook Lake", category: "Outdoors", lat: 32.6583, lng: -97.4578, address: "Multiple access points", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { 'Park Entry': 5, note: "per vehicle" }, hours: { all: "Varies" }, rating: 4.4, reviewCount: 400, reviewHighlights: ["Good for swimming", "Boating and fishing", "Campgrounds available"], tips: ["Several parks line the lake with swim beaches and picnic areas.", "Mustang Park is a popular spot for families.", "Check water levels before you go."] }),
    buildLocation(41, { name: "Amon Carter Museum of American Art", category: "Museum", lat: 32.7475, lng: -97.3675, address: "3501 Camp Bowie Blvd, Fort Worth, TX 76107", ageGroups: ["Teens"], price: "Free", hours: { Tue:"10:00-17:00", Wed:"10:00-17:00", Thu:"10:00-20:00", Fri:"10:00-17:00", Sat:"10:00-17:00", Sun:"12:00-17:00", Mon:"Closed" }, rating: 4.8, reviewCount: 450, reviewHighlights: ["Great American West art", "Beautiful building", "Always free"], tips: ["Focuses on American art, especially works of the American West by Remington and Russell.", "The photography collection is excellent.", "The view of downtown Fort Worth from the front porch is spectacular."] }),
    buildLocation(42, { name: "Texas Civil War Museum", category: "Museum", lat: 32.7214, lng: -97.4608, address: "760 Jim Wright Fwy, White Settlement, TX 76108", ageGroups: ["Teens"], price: "$", ticketInfo: { Admission: 7 }, hours: { Tue: "10:00-17:00", Wed: "10:00-17:00", Thu: "10:00-17:00", Fri: "10:00-17:00", Sat: "10:00-17:00", Sun: "Closed", Mon: "Closed" }, rating: 4.7, reviewCount: 300, reviewHighlights: ["Extensive collection", "Knowledgeable staff", "Focus on Texas history"], tips: ["Largest Civil War museum west of the Mississippi.", "Includes artifacts from both Union and Confederate sides.", "Good for a deep dive into history."] }),
    buildLocation(43, { name: "Flight Deck Trampoline Park", category: "Indoor", lat: 32.7303, lng: -97.1856, address: "7751 Scott St, Fort Worth, TX 76108", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { '1 Hour': 16, '2 Hours': 26 }, hours: { all: "Varies" }, rating: 4.4, reviewCount: 500, reviewHighlights: ["Great for burning energy", "Dodgeball is fun", "Book jump time online"], tips: ["Wear athletic clothing.", "They have special jump times for toddlers.", "Can get crowded, so booking ahead is recommended."] }),
    buildLocation(44, { name: "The Modern Art Museum of Fort Worth", category: "Museum", lat: 32.7485, lng: -97.3633, address: "3200 Darnell St, Fort Worth, TX 76107", ageGroups: ["Teens"], price: "$", ticketInfo: { Adult: 16, 'Free on Fridays': 'True' }, hours: { Tue:"10:00-17:00", Wed:"10:00-17:00", Thu:"10:00-17:00", Fri:"10:00-20:00", Sat:"10:00-17:00", Sun:"10:00-17:00", Mon:"Closed" }, rating: 4.7, reviewCount: 600, reviewHighlights: ["Amazing architecture", "Interesting collection", "Free on Fridays"], tips: ["Admission is free on Fridays.", "The building itself, designed by Tadao Ando, is a work of art.", "Great for teens interested in contemporary art."] }),
    buildLocation(45, { name: "Main Event", category: "Indoor", lat: 32.8398, lng: -97.1070, address: "Multiple DFW Locations", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { 'Varies by activity': 'See website' }, hours: { all: "Varies" }, rating: 4.2, reviewCount: 1100, reviewHighlights: ["Bowling, laser tag, arcade", "Something for everyone", "Can get expensive"], tips: ["Look for weekday deals or all-access passes.", "Good for groups or birthday parties.", "The food is standard arcade fare."] }),
    buildLocation(46, { name: "D-BAT", category: "Attraction", lat: 32.9620, lng: -97.2348, address: "Multiple DFW Locations", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { 'Cage Rental': 20, note: "prices vary" }, hours: { all: "Varies" }, rating: 4.6, reviewCount: 250, reviewHighlights: ["Batting cages", "Great for practice", "Clean facility"], tips: ["For the baseball or softball-loving kid.", "You can rent cages by the half-hour or hour.", "Offers private lessons as well."] }),
    buildLocation(47, { name: "Eagle Mountain Lake Park", category: "Park", lat: 32.8833, lng: -97.4794, address: "11601 Morris Dido Newark Rd, Fort Worth, TX 76179", ageGroups: ["Kids", "Teens"], price: "Free", hours: { all: "08:00-20:00" }, rating: 4.7, reviewCount: 500, reviewHighlights: ["Great hiking trails", "Beautiful lake views", "Can be rocky"], tips: ["More of a hiking spot than a playground park.", "The trails offer some of the best views in the DFW area.", "Wear sturdy shoes."] }),
    buildLocation(48, { name: "Dinosaur Valley State Park", category: "Outdoors", lat: 32.2514, lng: -97.8169, address: "1629 Park Rd 59, Glen Rose, TX 76043", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Adult: 7, 'Child 12 & Under': 0 }, hours: { all: "08:00-17:00" }, rating: 4.7, reviewCount: 1300, reviewHighlights: ["Real dinosaur tracks!", "River is fun to play in", "Check track conditions"], tips: ["A bit of a drive, but worth it.", "You can walk in real dinosaur footprints in the Paluxy River bed.", "Call ahead or check their Facebook page to ensure the tracks are visible and not covered by murky water."] }),
    buildLocation(49, { name: "Fossil Rim Wildlife Center", category: "Attraction", lat: 32.2598, lng: -97.8769, address: "2299 Co Rd 2008, Glen Rose, TX 76043", ageGroups: ["Toddlers", "Kids", "Teens"], price: "$", ticketInfo: { General: 29.95, note: "prices vary" }, hours: { all: "08:30-16:30" }, rating: 4.8, reviewCount: 1500, reviewHighlights: ["Feed animals from your car", "Giraffes are amazing", "Book tickets in advance"], tips: ["A drive-through safari experience.", "Buy a bag of animal feed at the entrance.", "The giraffes will stick their heads right in your car!"] }),
    buildLocation(50, { name: "Granbury City Beach Park", category: "Park", lat: 32.4400, lng: -97.7850, address: "505 E Pearl St, Granbury, TX 76048", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "07:00-22:00" }, rating: 4.5, reviewCount: 400, reviewHighlights: ["Nice little beach", "Spray park is great", "Right off the town square"], tips: ["A sandy beach on Lake Granbury.", "Has a small spray park for kids.", "A great way to cool off after exploring the historic Granbury square."] }),
    
    // === NEW LOCATIONS (51-85) ===
    
    // FREE INDOOR ACTIVITIES
    buildLocation(51, { name: "Frisco Public Library", category: "Indoor", lat: 33.1507, lng: -96.8236, address: "6101 Frisco Square Blvd, Frisco, TX 75034", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { Mon: "10:00-21:00", Tue: "10:00-21:00", Wed: "10:00-21:00", Thu: "10:00-21:00", Fri: "10:00-18:00", Sat: "10:00-18:00", Sun: "13:00-18:00" }, rating: 4.8, reviewCount: 450, reviewHighlights: ["Amazing children's section", "Story time programs", "Modern and clean"], tips: ["Free story time sessions - check schedule online.", "Has a dedicated maker space for kids.", "One of the most modern libraries in DFW."] }),
    buildLocation(52, { name: "Irving Public Library - Central", category: "Indoor", lat: 32.8140, lng: -96.9489, address: "801 W Irving Blvd, Irving, TX 75060", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { Mon: "10:00-21:00", Tue: "10:00-21:00", Wed: "10:00-21:00", Thu: "10:00-21:00", Fri: "10:00-18:00", Sat: "10:00-18:00", Sun: "13:00-18:00" }, rating: 4.7, reviewCount: 380, reviewHighlights: ["Great children's programs", "Spacious reading areas", "Free WiFi"], tips: ["Offers free kids programs year-round.", "Has computers and tablets for kids to use.", "Cool architecture with lots of natural light."] }),
    buildLocation(53, { name: "McKinney Public Library", category: "Indoor", lat: 33.1974, lng: -96.6153, address: "101 E Hunt St, McKinney, TX 75069", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { Mon: "10:00-21:00", Tue: "10:00-21:00", Wed: "10:00-21:00", Thu: "10:00-21:00", Fri: "10:00-18:00", Sat: "10:00-18:00", Sun: "13:00-17:00" }, rating: 4.8, reviewCount: 420, reviewHighlights: ["Beautiful historic building", "Excellent kids section", "Free events"], tips: ["Located in historic downtown McKinney.", "Regular story times and craft activities.", "Great place to escape the heat."] }),
    buildLocation(54, { name: "Grapevine Public Library", category: "Indoor", lat: 32.9342, lng: -97.0781, address: "1201 Municipal Way, Grapevine, TX 76051", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { Mon: "10:00-21:00", Tue: "10:00-21:00", Wed: "10:00-21:00", Thu: "10:00-21:00", Fri: "10:00-18:00", Sat: "10:00-18:00", Sun: "13:00-17:00" }, rating: 4.7, reviewCount: 350, reviewHighlights: ["Interactive children's area", "Summer reading program", "Friendly staff"], tips: ["Check calendar for special events.", "Has a teen zone with games and activities.", "Free parking in adjacent lot."] }),
    buildLocation(55, { name: "Flower Mound Public Library", category: "Indoor", lat: 33.0290, lng: -97.0869, address: "3030 Broadmoor Ln, Flower Mound, TX 75022", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { Mon: "10:00-21:00", Tue: "10:00-21:00", Wed: "10:00-21:00", Thu: "10:00-21:00", Fri: "10:00-18:00", Sat: "10:00-18:00", Sun: "13:00-17:00" }, rating: 4.8, reviewCount: 390, reviewHighlights: ["Huge selection", "Great study areas", "Kids programs"], tips: ["One of the larger libraries in the area.", "Has a dedicated early literacy space.", "Free museum passes available for checkout."] }),
    buildLocation(56, { name: "Bass Performance Hall Tours", category: "Indoor", lat: 32.7513, lng: -97.3292, address: "525 Commerce St, Fort Worth, TX 76102", ageGroups: ["Kids", "Teens"], price: "Free", hours: { Mon: "10:00-14:00", Tue: "10:00-14:00", Wed: "10:00-14:00", Thu: "10:00-14:00", Fri: "10:00-14:00", Sat: "10:00-14:00", Sun: "Closed" }, rating: 4.9, reviewCount: 280, reviewHighlights: ["Stunning architecture", "Free guided tours", "Educational experience"], tips: ["Free guided tours available - check schedule.", "Beautiful building even if you don't see a show.", "Great introduction to performing arts."] }),
    buildLocation(57, { name: "Galleria Dallas Ice Skating", category: "Indoor", lat: 32.9345, lng: -96.8357, address: "13350 Dallas Pkwy, Dallas, TX 75240", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Admission: 10, 'Skate Rental': 5 }, hours: { Mon: "10:00-21:00", Tue: "10:00-21:00", Wed: "10:00-21:00", Thu: "10:00-21:00", Fri: "10:00-22:00", Sat: "10:00-22:00", Sun: "12:00-18:00" }, rating: 4.4, reviewCount: 620, reviewHighlights: ["Year-round ice skating", "Great for all skill levels", "Can get crowded"], tips: ["Indoor ice rink in the middle of a mall.", "Good for a quick activity while shopping.", "Weekday mornings are less crowded."] }),

    // WEATHERFORD & WESTERN SUBURBS
    buildLocation(58, { name: "Splash Kingdom Waterpark", category: "Waterpark", lat: 33.0890, lng: -97.5926, address: "9001 Safari Rd, Weatherford, TX 76087", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { General: 36 }, hours: { all: "Varies (Seasonal)" }, rating: 4.6, reviewCount: 580, reviewHighlights: ["Great slides", "Not too big or overwhelming", "Clean facilities"], tips: ["Smaller than the mega water parks, perfect for younger kids.", "Season passes available if you go often.", "Can bring your own cooler."] }),
    buildLocation(59, { name: "Weatherford Public Library", category: "Indoor", lat: 32.7593, lng: -97.7969, address: "1014 Charles St, Weatherford, TX 76086", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { Mon: "10:00-20:00", Tue: "10:00-20:00", Wed: "10:00-20:00", Thu: "10:00-20:00", Fri: "10:00-18:00", Sat: "10:00-17:00", Sun: "Closed" }, rating: 4.6, reviewCount: 280, reviewHighlights: ["Cozy atmosphere", "Good kids section", "Helpful staff"], tips: ["Great free option in Weatherford.", "Regular story times and kids programs.", "Has study rooms you can reserve."] }),
    buildLocation(60, { name: "Mineral Wells Fossil Park", category: "Outdoors", lat: 32.8090, lng: -98.1128, address: "Highway 180 & 281, Mineral Wells, TX 76067", ageGroups: ["Kids", "Teens"], price: "Free", hours: { all: "Sunrise-Sunset" }, rating: 4.7, reviewCount: 320, reviewHighlights: ["Find real fossils!", "Educational and fun", "Bring tools"], tips: ["You can actually dig for and keep fossils!", "Bring a small hammer and safety glasses.", "Best after rain when fossils are easier to spot."] }),
    buildLocation(61, { name: "Possum Kingdom State Park", category: "Outdoors", lat: 32.8573, lng: -98.4389, address: "3129 Park Rd 33, Caddo, TX 76429", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Adult: 7, 'Child 12 & Under': 0 }, hours: { all: "08:00-22:00" }, rating: 4.6, reviewCount: 450, reviewHighlights: ["Beautiful lake views", "Great camping", "Swimming and hiking"], tips: ["One of the prettiest lakes in Texas.", "Has swimming beaches and hiking trails.", "Popular for camping - book ahead."] }),

    // SOUTHERN CORRIDOR
    buildLocation(62, { name: "Lynn Creek Park", category: "Park", lat: 32.6770, lng: -96.9930, address: "5500 Parkwood Way, Grand Prairie, TX 75052", ageGroups: ["Toddlers", "Kids", "Teens"], price: "$", ticketInfo: { 'Park Entry': 10, note: "per vehicle" }, hours: { all: "06:00-22:00" }, rating: 4.5, reviewCount: 520, reviewHighlights: ["Great swimming area", "Nice playground", "Shaded picnic spots"], tips: ["On Joe Pool Lake with a sandy beach.", "Has a playground, volleyball courts, and boat ramps.", "Get there early on summer weekends."] }),
    buildLocation(63, { name: "Joe Pool Lake", category: "Outdoors", lat: 32.6583, lng: -97.0078, address: "Multiple access points", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { 'Park Entry': 5, note: "per vehicle" }, hours: { all: "Varies by location" }, rating: 4.4, reviewCount: 680, reviewHighlights: ["Good fishing", "Multiple parks around lake", "Boating access"], tips: ["Several parks provide access: Lynn Creek, Loyd Park, etc.", "Popular for fishing and boating.", "Each park has different amenities."] }),
    buildLocation(64, { name: "Loyd Park", category: "Park", lat: 32.6283, lng: -97.0489, address: "3401 Ragland Rd, Grand Prairie, TX 75052", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { 'Park Entry': 10, note: "per vehicle" }, hours: { all: "06:00-22:00" }, rating: 4.5, reviewCount: 490, reviewHighlights: ["Nice campground", "Swimming beach", "Mountain bike trails"], tips: ["Has camping, swimming, and trails.", "Mountain bike trails are challenging and fun.", "Popular for birthday parties."] }),
    buildLocation(65, { name: "Cedar Hill State Park", category: "Outdoors", lat: 32.6267, lng: -96.9856, address: "1570 FM 1382, Cedar Hill, TX 75104", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Adult: 7, 'Child 12 & Under': 0 }, hours: { all: "06:00-22:00" }, rating: 4.6, reviewCount: 780, reviewHighlights: ["Great hiking trails", "Lake swimming", "Clean facilities"], tips: ["Excellent hiking with hill country views.", "Swimming beach on Joe Pool Lake.", "Good for mountain biking too."] }),
    buildLocation(66, { name: "Armstrong Park", category: "Park", lat: 32.5883, lng: -96.9028, address: "2400 S Main St, Duncanville, TX 75137", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "06:00-23:00" }, rating: 4.6, reviewCount: 340, reviewHighlights: ["Large playground", "Splash pad", "Walking trails"], tips: ["One of Duncanville's best parks.", "Splash pad is popular in summer.", "Has covered pavilions for parties."] }),
    buildLocation(67, { name: "Duncanville Library", category: "Indoor", lat: 32.6518, lng: -96.9083, address: "201 James Collins Blvd, Duncanville, TX 75116", ageGroups: ["Toddlers", "Kids", "Teens"], price: "Free", hours: { Mon: "10:00-20:00", Tue: "10:00-20:00", Wed: "10:00-20:00", Thu: "10:00-20:00", Fri: "10:00-18:00", Sat: "10:00-17:00", Sun: "Closed" }, rating: 4.7, reviewCount: 290, reviewHighlights: ["Great kids programs", "Modern facility", "Helpful librarians"], tips: ["Free story times and activities.", "Has a teen zone with gaming.", "Good free option in the area."] }),
    buildLocation(68, { name: "DeSoto Town Center", category: "Outdoors", lat: 32.5899, lng: -96.8570, address: "211 E Pleasant Run Rd, DeSoto, TX 75115", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "Varies" }, rating: 4.4, reviewCount: 310, reviewHighlights: ["Splash pad", "Playground", "Free events"], tips: ["Nice community gathering spot.", "Has splash pad and playground.", "Hosts free events and concerts."] }),

    // UNIQUE EXPERIENCES
    buildLocation(69, { name: "Texas Discovery Gardens", category: "Outdoors", lat: 32.7855, lng: -96.7669, address: "3601 Martin Luther King Jr Blvd, Dallas, TX 75210", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Adult: 10, Child: 8 }, hours: { Tue: "10:00-17:00", Wed: "10:00-17:00", Thu: "10:00-17:00", Fri: "10:00-17:00", Sat: "10:00-17:00", Sun: "10:00-17:00", Mon: "Closed" }, rating: 4.6, reviewCount: 420, reviewHighlights: ["Beautiful butterfly house", "Native Texas plants", "Educational"], tips: ["Indoor butterfly habitat is the highlight.", "Located in Fair Park.", "Great for nature lovers."] }),
    buildLocation(70, { name: "Zero Gravity Thrill Amusement Park", category: "Attraction", lat: 32.7700, lng: -97.0789, address: "11131 Malibu Dr, Dallas, TX 75229", ageGroups: ["Teens"], price: "$", ticketInfo: { 'Per Ride': '25-45', note: 'varies by ride' }, hours: { Fri: "17:00-23:00", Sat: "12:00-23:00", Sun: "12:00-21:00", Mon: "Closed", Tue: "Closed", Wed: "Closed", Thu: "Closed" }, rating: 4.5, reviewCount: 510, reviewHighlights: ["Extreme thrill rides", "Nothin Butt Net is insane", "Not for young kids"], tips: ["For teens and adults who love extreme rides.", "Each ride is separately priced.", "Must sign waiver."] }),
    buildLocation(71, { name: "Hawaiian Falls Waterparks", category: "Waterpark", lat: 33.0318, lng: -96.9278, address: "Multiple DFW Locations", ageGroups: ["Toddlers", "Kids", "Teens"], price: "$", ticketInfo: { General: 35, note: 'prices vary' }, hours: { all: "Varies (Seasonal)" }, rating: 4.3, reviewCount: 890, reviewHighlights: ["Multiple locations", "Good for families", "Can get crowded"], tips: ["Several locations across DFW.", "Season passes are good value if you go multiple times.", "Weekdays are less crowded."] }),
    buildLocation(72, { name: "Urban Air Trampoline Park", category: "Indoor", lat: 32.9875, lng: -96.7590, address: "Multiple DFW Locations", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { '1 Hour': 20, '2 Hours': 34 }, hours: { all: "10:00-21:00" }, rating: 4.2, reviewCount: 720, reviewHighlights: ["Good variety of activities", "More than just trampolines", "Can get busy"], tips: ["Has dodgeball, climbing walls, and more.", "Book jump time online.", "Multiple DFW locations."] }),
    buildLocation(73, { name: "Pincus Mound Park", category: "Park", lat: 32.9584, lng: -96.8264, address: "5710 Pincus St, The Colony, TX 75056", ageGroups: ["Toddlers", "Kids"], price: "Free", hours: { all: "06:00-23:00" }, rating: 4.7, reviewCount: 380, reviewHighlights: ["Amazing playground", "Unique mound design", "Lots of shade"], tips: ["Built on an interesting hill/mound.", "Has tunnels and unique play structures.", "Great views from the top."] }),
    buildLocation(74, { name: "Texas Motor Speedway", category: "Attraction", lat: 33.0373, lng: -97.2814, address: "3545 Lone Star Cir, Fort Worth, TX 76177", ageGroups: ["Kids", "Teens"], price: "$$", ticketInfo: { 'Track Tours': 10, 'Race Tickets': 'Varies' }, hours: { all: "Varies by event" }, rating: 4.6, reviewCount: 1200, reviewHighlights: ["NASCAR races", "Great atmosphere", "Loud!"], tips: ["Offers tours when races aren't happening.", "Race tickets vary widely by event.", "Bring ear protection for kids."] }),
    buildLocation(75, { name: "Cavanaugh Flight Museum", category: "Museum", lat: 32.8472, lng: -96.8358, address: "4572 Claire Chennault St, Addison, TX 75001", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Adult: 12, Child: 8 }, hours: { Mon: "10:00-17:00", Tue: "10:00-17:00", Wed: "10:00-17:00", Thu: "10:00-17:00", Fri: "10:00-17:00", Sat: "10:00-17:00", Sun: "11:00-17:00" }, rating: 4.7, reviewCount: 380, reviewHighlights: ["Amazing aircraft collection", "Interactive exhibits", "Great for plane enthusiasts"], tips: ["Features restored vintage aircraft.", "Some planes are still flown.", "Great for kids interested in aviation."] }),

    // POPULAR FAVORITES
    buildLocation(76, { name: "Dallas Museum of Art", category: "Museum", lat: 32.7876, lng: -96.8010, address: "1717 N Harwood St, Dallas, TX 75201", ageGroups: ["Kids", "Teens"], price: "Free", hours: { Tue: "11:00-17:00", Wed: "11:00-17:00", Thu: "11:00-21:00", Fri: "11:00-21:00", Sat: "11:00-17:00", Sun: "11:00-17:00", Mon: "Closed" }, rating: 4.7, reviewCount: 1400, reviewHighlights: ["Free general admission", "World-class collection", "Family programs"], tips: ["General admission is always free.", "Has special family programs and tours.", "The ancient art section is fascinating."] }),
    buildLocation(77, { name: "Six Flags Over Texas", category: "Attraction", lat: 32.7553, lng: -97.0706, address: "2201 E Road to Six Flags St, Arlington, TX 76011", ageGroups: ["Kids", "Teens"], price: "$$", ticketInfo: { General: 75, note: 'prices vary' }, hours: { all: "Varies by season" }, rating: 4.4, reviewCount: 2800, reviewHighlights: ["Classic theme park", "Great coasters", "Can be expensive"], tips: ["Buy tickets online for better prices.", "Go on weekdays to avoid crowds.", "Bring sunscreen and water."] }),
    buildLocation(78, { name: "Six Flags Hurricane Harbor", category: "Waterpark", lat: 32.7622, lng: -97.0842, address: "1800 E Lamar Blvd, Arlington, TX 76006", ageGroups: ["Kids", "Teens"], price: "$$", ticketInfo: { General: 55, note: 'prices vary' }, hours: { all: "Varies (Seasonal)" }, rating: 4.3, reviewCount: 1900, reviewHighlights: ["Big water park", "Lots of slides", "Gets very crowded"], tips: ["Largest water park in DFW.", "Arrive at opening for shorter lines.", "Season passes pay for themselves in 2-3 visits."] }),
    buildLocation(79, { name: "Reunion Tower", category: "Attraction", lat: 32.7755, lng: -96.8089, address: "300 Reunion Blvd E, Dallas, TX 75207", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Adult: 22, Child: 17 }, hours: { all: "10:00-22:00" }, rating: 4.6, reviewCount: 2100, reviewHighlights: ["Amazing views", "Interactive displays", "Great at sunset"], tips: ["360-degree views of Dallas from 470 feet up.", "Visit at sunset for best experience.", "Has interactive displays about DFW."] }),
    buildLocation(80, { name: "AT&T Stadium Tours", category: "Attraction", lat: 32.7473, lng: -97.0945, address: "1 AT&T Way, Arlington, TX 76011", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Adult: 32, Child: 24 }, hours: { all: "10:00-17:00" }, rating: 4.7, reviewCount: 1600, reviewHighlights: ["Impressive stadium", "Great tours", "Cowboys history"], tips: ["Tours of the Dallas Cowboys stadium.", "See the field, locker rooms, and more.", "Book tours in advance."] }),
    buildLocation(81, { name: "Globe Life Field Tour", category: "Attraction", lat: 32.7472, lng: -97.0828, address: "734 Stadium Dr, Arlington, TX 76011", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Adult: 25, Child: 20 }, hours: { all: "Varies" }, rating: 4.6, reviewCount: 890, reviewHighlights: ["Beautiful new stadium", "Behind-the-scenes access", "Rangers history"], tips: ["Texas Rangers' new stadium opened in 2020.", "Tours include dugout and press box.", "Air conditioned - great in summer!"] }),
    buildLocation(82, { name: "The Sixth Floor Museum", category: "Museum", lat: 32.7798, lng: -96.8085, address: "411 Elm St, Dallas, TX 75202", ageGroups: ["Teens"], price: "$", ticketInfo: { Adult: 18, Youth: 14 }, hours: { Mon: "10:00-18:00", Tue: "10:00-18:00", Wed: "10:00-18:00", Thu: "10:00-18:00", Fri: "10:00-18:00", Sat: "10:00-18:00", Sun: "12:00-18:00" }, rating: 4.8, reviewCount: 1700, reviewHighlights: ["Important history", "Very moving", "Well presented"], tips: ["About JFK's assassination in Dallas.", "Best for older kids and teens.", "Audio tour is excellent."] }),
    buildLocation(83, { name: "Top Golf", category: "Indoor", lat: 33.0123, lng: -96.8456, address: "Multiple DFW Locations", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { 'Per Hour': 30, note: 'per bay, shared' }, hours: { all: "09:00-23:00" }, rating: 4.4, reviewCount: 1500, reviewHighlights: ["Fun for all skill levels", "Good food", "Can get pricey"], tips: ["Golf entertainment venue - no experience needed.", "Pricing is per bay (up to 6 people share).", "Multiple DFW locations."] }),
    buildLocation(84, { name: "Traders Village", category: "Outdoors", lat: 32.8856, lng: -97.0078, address: "2602 Mayfield Rd, Grand Prairie, TX 75052", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Parking: 5 }, hours: { Sat: "08:00-18:00", Sun: "10:00-17:00", Mon: "Closed", Tue: "Closed", Wed: "Closed", Thu: "Closed", Fri: "Closed" }, rating: 4.3, reviewCount: 1100, reviewHighlights: ["Huge flea market", "Carnival rides on weekends", "Great for bargain hunting"], tips: ["Giant weekend flea market.", "Has carnival rides for kids.", "Parking fee but entry is free."] }),
    buildLocation(85, { name: "Frontiers of Flight Museum", category: "Museum", lat: 32.8475, lng: -96.8356, address: "6911 Lemmon Ave, Dallas, TX 75209", ageGroups: ["Kids", "Teens"], price: "$", ticketInfo: { Adult: 12, Child: 8 }, hours: { Mon: "10:00-17:00", Tue: "10:00-17:00", Wed: "10:00-17:00", Thu: "10:00-17:00", Fri: "10:00-17:00", Sat: "10:00-17:00", Sun: "13:00-17:00" }, rating: 4.6, reviewCount: 520, reviewHighlights: ["Great aircraft displays", "Interactive exhibits", "Love Field location"], tips: ["At Dallas Love Field airport.", "Has actual planes you can board.", "Good for budding pilots."] })
];